 services:
  - type: web
    name: interactive-resume-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: MONGO_URI
        value: ${MONGO_URI}  
        
    plan: free
    region: oregon

staticSites:
  - name: interactive-resume-frontend
    buildCommand: ""
    staticPublishPath: frontend
    indexDocument: index.html
    errorDocument: index.html
