services:
  - type: web
    name: interactive-resume-backend
    env: python
    region: oregon
    buildCommand: ""
    startCommand: "python backend/app.py"
    runtime: python
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        sync: false
