services:
  - type: web
    name: interactive-resume
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --timeout 90
    envVars:
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: DB_NAME
        value: interactive_resume
    plan: free
    region: oregon
