 services:
  - type: web
    name: interactive-resume-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://yashch11:U3IPZtG8wTRq8C2j@cluster0.9esovcd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    plan: free
    region: oregon

staticSites:
  - name: interactive-resume-frontend
    buildCommand: ""
    staticPublishPath: frontend
    indexDocument: index.html
    errorDocument: index.html
